version: "2"

run:
  timeout: 5m
  tests: false # Set to true if you want to lint test files as well
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.md$"
    - ".*\\.MD$"

linters:
  default: none
  enable:
    # --- Core Linters (Must Have) ---
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs (standard Go tool)
    - gosec         # Security analyzer for Go code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple)
    - unused        # Detect unused constants, variables, and functions

    # --- Style & Formatting ---
    - misspell      # Detect spelling mistakes in English
    - revive        # Modern replacement for golint, enforces coding style

    # --- Complexity ---
    - gocyclo       # Check cyclomatic complexity of functions

  settings:
    govet:
      enable:
        - shadow

    errcheck:
      check-type-assertions: true
      exclude-functions:
         # fmt.Fprintf/Fprintln errors are typically safe to ignore for logging
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (fmt).Fprintf
        - (fmt).Fprintln

    gocyclo:
      min-complexity: 15 # Report functions with excessive complexity (too many if/else branches)

    misspell:
      locale: US

  exclusions:
    generated: strict

formatters:
  enable:
    - gofmt         # Check code formatting against Go standards
    - goimports     # Automatically organize and format imports

  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
