run:
  timeout: 5m
  tests: false # Set to true if you want to lint test files as well

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 15 # Report functions with excessive complexity (too many if/else branches)
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    # --- Core Linters (Must Have) ---
    - errcheck      # Check for unchecked errors
    - gosimple      # Suggest code simplifications
    - govet         # Report suspicious constructs (standard Go tool)
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis for bugs and performance issues
    - typecheck     # Parse and type-check Go code
    - unused        # Detect unused constants, variables, and functions

    # --- Style & Formatting ---
    - gofmt         # Check code formatting against Go standards
    - goimports     # Automatically organize and format imports
    - misspell      # Detect spelling mistakes in English
    - revive        # Modern replacement for golint, enforces coding style

    # --- Complexity ---
    - gocyclo       # Check cyclomatic complexity of functions

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0